### ISSUE TITLE
Write introduction

### ISSUE THREAD

**Issue by drom** [drom/bitfield#2]

**Comment by bavovanachte** [comment]
A note on how to embed this in html would also be very helpful. If possible, I intend to write a sphinx plugin for this, as I'm doing for wavedrom here: https://github.com/bavovanachte/sphinx-wavedrom

**Comment by drom** [comment]
@bavovanachte good idea. WIll do.

**Comment by drom** [comment]
This project is part of wavedrom. Embed in HTML using https://github.com/wavedrom/wavedrom
