### ISSUE TITLE
Support for `--bigendian true`

### ISSUE THREAD

**Issue by kevbroch** [drom/bitfield#22]
Looking at the code here: https://github.com/drom/bitfield/blob/master/lib/render.js#L209
I don't see how setting `--bigendian true` does anything

**Comment by drom** [comment]
True. This feature was requested but never been properly implemented. Do you plan using it?

**Comment by kevbroch** [comment]
Yes, that was my hope.

**Comment by smnice** [comment]
Hi @drom ,
I discovered WaveDrom by reading your interview with electronicdesign, that you posted recently on LinkedIn. I am part of a project that builds a document drafting framework (with focus on Technical Norms/Standards such as IETF, IEEE, ETSI etc.) and big-endianness is the dominant ordering in networking protocols. Often message descriptions as in the following picture are required:   

![image](https://user-images.githubusercontent.com/18146734/79500451-b877d980-802c-11ea-8351-838c0e1ac657.png)

Hence my interest in the bitfield library and especially on the big-endian feature. What would be your advice on how to progress best with this feature ?

**Comment by drom** [comment]
It should be too hard. Let me try.

**Comment by drom** [comment]
I ended up implementing 2 options instead of **bigendian** option in v1.3.1:
* Horizontal flip -- **hflip**
* Vertical flip -- **vflip**

You can see how they work here: https://observablehq.com/@drom/bitfield-testbox

**Comment by smnice** [comment]
Hi @drom ,
Thanks a lot for this update ! The options {compact: true, vflip: true, hflip: true} provide the rendering that is most often used in our standards. Very impressive your tool. We will implement a prototype in our platform. I will keep you posted.

**Comment by drom** [comment]
@smnice looking forward to seeing your prototype.
Closing this ticket.
