### ISSUE TITLE
Is it possible to display all the numbers?

### ISSUE THREAD

**Issue by ghost** [drom/bitfield#37]
Like this:

## Now
![](https://raw.githubusercontent.com/gist/PYGC/983b338195a4263c7631d126c4c77cb9/raw/2f7f96c285e288df3046dfd6afb34cd75bebf30f/PWR_CR4.svg)

## Show all number
![](https://raw.githubusercontent.com/gist/PYGC/983b338195a4263c7631d126c4c77cb9/raw/2f7f96c285e288df3046dfd6afb34cd75bebf30f/PWR_CR4_show_all_number.svg)

**Comment by ghost** [comment]
Thank you very much

**Comment by drom** [comment]
not right now. Is it useful?
