### ISSUE TITLE
Auto detect total number of bits

### ISSUE THREAD

**Issue by furkanusta** [drom/bitfield#40]
Hi, I've added a feature to auto-detect the number of bits by summing all in the input file. 

I wasn't sure whether to use a numeric default (e.g. -1, 0), a string default ('auto') or 'undefined' so I went with the last one.

I can open a PR if you are interested.

Here is the code if you want to check
63a46c3ebf6db379f47542d00b3ad73f4208ad52

**Comment by drom** [comment]
PR is welcome
